version: '3.3'
services:
    nexus3:
        ports:
            - '8081:8081'
        container_name: nexus-server
        volumes:
            - 'nexus-data:/nexus-data'
        environment:
                - NEXUS_CONTEXT=nexus
        image: sonatype/nexus3:latest
volumes:
        nexus-data:
                driver: local
