version: '3.3'
services:
   tomcat:
    container_name: tomcat_service
    image: tomcat:jdk17-openjdk-slim
    volumes:
      - ./tomcat-init/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat-init/webapps/:/usr/local/tomcat/webapps/
    ports:
      - '8081:8080'
