version: '3.3'
services:
   jenkins:
     image: jenkins/jenkins:lts-jdk11
     container_name: jenkins
     volumes:
       - ./jenkins_home:/var/lib/jenkins_home
       - /usr/bin/mvn:/usr/bin/mvn
     ports:
       - 8080:8080
       - 50000:50000
