version: '3.3'
services:
   mysql-database:
     image: mysql:8.0
     container_name: mysql-database
     volumes:
       - ./mysql-data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_USER: webs
       MYSQL_PASSWORD: test
     ports:
       - 3306:3306
   phpmyadmin:
    depends_on:
      - mysql-database
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql-database
      MYSQL_ROOT_PASSWORD: root
